[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ast = true
build_info = true
extra_output = ["storageLayout"]
solc_version = "0.8.23"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
mode = "https://mainnet.mode.network"
base = "https://mainnet.base.org"
optimism = "https://mainnet.optimism.io"
bob = "https://rpc.gobob.xyz"
fraxtal = "https://rpc.frax.com"